<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ImageViewer</AssemblyName>
    <RootNamespace>ImageViewer</RootNamespace>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Include="native\libraw.dll" CopyToOutputDirectory="PreserveNewest" Link="libraw.dll" />
    <None Include="native\heif.dll" CopyToOutputDirectory="PreserveNewest" Link="heif.dll" />
    <None Include="native\libde265.dll" CopyToOutputDirectory="PreserveNewest" Link="libde265.dll" />
    <None Include="native\dav1d.dll" CopyToOutputDirectory="PreserveNewest" Link="dav1d.dll" />
  </ItemGroup>

</Project>
